[package]
name = "solving-minecraftle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.86"
itertools = "0.13.0"
serde_json = "1.0.122"
